services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./logs:/var/log/nginx
            - .:/var/www
        links:
            - php
        environment:
            - DOMAIN=${DOMAIN}
        command:
            /bin/bash -c "envsubst '$$DOMAIN' < /etc/nginx/conf.d/template > /etc/nginx/conf.d/default.conf &&
            envsubst '$$DOMAIN' < /etc/nginx/conf.d/template_backend > /etc/nginx/conf.d/backend.apple.conf &&  
            nginx -g 'daemon off;'"

    php:
        build:
            context: .
            dockerfile: Dockerfile
        user: "1000:1000"
        links:
            - db
        working_dir: /var/www
        volumes:
            - .:/var/www
        expose:
            - 9000
        environment:
            - TZ=Europe/Moscow
    db:
        image: mysql:latest
        command: --max_allowed_packet=325058560
        ports:
            - 3306:3306
        volumes:
            - ./storage/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
